[build]
command = "npm ci && npm run build"
publish = "dist"
base = "/"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--legacy-peer-deps --force"
CI = "false"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[functions]
directory = "netlify/functions"

[dev]
framework = "#custom"
command = "npm run dev"
targetsPort = 3000
port = 8888

[build.processing]
skip_processing = false

[build.processing.html]
pretty_urls = true

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.images]
compress = true
